namespace Dalmarkit.Common.PubSub;

public class TopicMessage<TPayload>
{
    /// <summary>
    /// Logical idempotency key
    /// Generated by the publishing envelope (Guid.NewGuid().ToString("D")) when the caller does not supply one
    /// Stable across producer retries and replays so consumers' <c>IIdempotencyStore</c> can dedupe messages
    /// even when Kafka assigns different (topic, partition, offset) tuples to the same logical event
    /// </summary>
    public required string BusinessMessageId { get; set; }

    public required string Method { get; set; }

    public required TPayload? Payload { get; set; }

    public required DateTimeOffset PublishTimestamp { get; set; }

    public required string Topic { get; set; }
}
